### ISSUE TITLE
Allow for future improvements to regexp syntax

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/wbnf#9]
(This might be a storm in a teacup. We could hold off 1.0 until we arrive at a syntax that isn't vulnerable to future breaking changes.)

#8 proposes a change to regexp syntax. The change is non-trivial to implement, since the current implementation simply defers to [re2](https://github.com/google/re2/wiki/Syntax). Consequently, it's not likely we'll tackle it anytime soon.

Think of a way to allow for future syntax improvements without having to introduce backwards incompatible changes to the language.

One option is to revert to `/.../` syntax for re2 and reserve `/{...}` syntax for a new and improved syntax.

**Comment by ChloePlanet** [comment]
Won't fix.
